import { Subscriptions } from "@/types/subscription";

const subscriptions: Subscriptions[] = [
  {
    id: 1,
    originalPrice: 1.33,
    displayPrice: "per day",
    rate: "month",
    tenure: 1,
    discount: 50,
    discountedPrice: 0.66,
    popular: false,
    totalPrice: 19.99,
    totalPriceWithFirstTimeDiscount: 17.99,
    totalPriceWithSecondTimeDiscount: 15.99,
    firstTimeDiscount: 70,
    secondTimeDiscount: 75,
    firstTimeDiscountedPricePerDay: 0.59,
    secondTimeDiscountedPricePerDay: 0.53,
  },
  {
    id: 2,
    originalPrice: 1.11,
    displayPrice: "per day",
    rate: "month",
    tenure: 12,
    discount: 70,
    discountedPrice: 0.33,
    popular: true,
    totalPrice: 119.99,
    totalPriceWithFirstTimeDiscount: 115.99,
    totalPriceWithSecondTimeDiscount: 109.99,
    firstTimeDiscount: 90,
    secondTimeDiscount: 95,
    firstTimeDiscountedPricePerDay: 0.32,
    secondTimeDiscountedPricePerDay: 0.3,
  },
  {
    id: 3,
    originalPrice: 1.22,
    displayPrice: "per day",
    rate: "month",
    tenure: 3,
    discount: 60,
    discountedPrice: 0.48,
    totalPrice: 43.99,
    totalPriceWithFirstTimeDiscount: 39.99,
    totalPriceWithSecondTimeDiscount: 37.99,
    popular: false,
    firstTimeDiscount: 80,
    secondTimeDiscount: 85,
    firstTimeDiscountedPricePerDay: 0.44,
    secondTimeDiscountedPricePerDay: 0.42,
  },
];

export default subscriptions;
